// Code generated by protoc-gen-go.
// source: idp.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	idp.proto

It has these top-level messages:
	User
	Device
	Error
	AcquireCaptchaReq
	AcquireCaptchaRsp
	VerifyCaptchaReq
	VerifyCaptchaRsp
	RegisterUserReq
	RegisterUserRsp
	BindDeviceReq
	BindDeviceRsp
	VerifyDeviceReq
	VerifyDeviceRsp
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// which way to unique a user
type SignUpType int32

const (
	SignUpType_EMAIL  SignUpType = 0
	SignUpType_MOBILE SignUpType = 1
)

var SignUpType_name = map[int32]string{
	0: "EMAIL",
	1: "MOBILE",
}
var SignUpType_value = map[string]int32{
	"EMAIL":  0,
	"MOBILE": 1,
}

func (x SignUpType) String() string {
	return proto.EnumName(SignUpType_name, int32(x))
}
func (SignUpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// device OS
type DeviceOS int32

const (
	DeviceOS_UNKONWN DeviceOS = 0
	DeviceOS_MAC     DeviceOS = 1
	DeviceOS_LINUX   DeviceOS = 2
	DeviceOS_UNIX    DeviceOS = 3
	DeviceOS_WINDOWS DeviceOS = 4
	DeviceOS_IOS     DeviceOS = 5
	DeviceOS_ANDROID DeviceOS = 6
)

var DeviceOS_name = map[int32]string{
	0: "UNKONWN",
	1: "MAC",
	2: "LINUX",
	3: "UNIX",
	4: "WINDOWS",
	5: "IOS",
	6: "ANDROID",
}
var DeviceOS_value = map[string]int32{
	"UNKONWN": 0,
	"MAC":     1,
	"LINUX":   2,
	"UNIX":    3,
	"WINDOWS": 4,
	"IOS":     5,
	"ANDROID": 6,
}

func (x DeviceOS) String() string {
	return proto.EnumName(DeviceOS_name, int32(x))
}
func (DeviceOS) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// device for
type DeviceFor int32

const (
	DeviceFor_FARMER     DeviceFor = 0
	DeviceFor_LEDGER     DeviceFor = 1
	DeviceFor_TELLER     DeviceFor = 2
	DeviceFor_SUPERVISOR DeviceFor = 3
	DeviceFor_IDPROVIDER DeviceFor = 4
)

var DeviceFor_name = map[int32]string{
	0: "FARMER",
	1: "LEDGER",
	2: "TELLER",
	3: "SUPERVISOR",
	4: "IDPROVIDER",
}
var DeviceFor_value = map[string]int32{
	"FARMER":     0,
	"LEDGER":     1,
	"TELLER":     2,
	"SUPERVISOR": 3,
	"IDPROVIDER": 4,
}

func (x DeviceFor) String() string {
	return proto.EnumName(DeviceFor_name, int32(x))
}
func (DeviceFor) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ErrorType int32

const (
	ErrorType_NONE_ERROR      ErrorType = 0
	ErrorType_INVALID_PARAM   ErrorType = 1
	ErrorType_INTERNAL_ERROR  ErrorType = 2
	ErrorType_ALREADY_SIGNUP  ErrorType = 3
	ErrorType_INVALID_CAPTCHA ErrorType = 4
	ErrorType_INVALID_USERID  ErrorType = 5
	ErrorType_ALREADY_DEVICE  ErrorType = 6
	ErrorType_INVALID_DEVICE  ErrorType = 7
)

var ErrorType_name = map[int32]string{
	0: "NONE_ERROR",
	1: "INVALID_PARAM",
	2: "INTERNAL_ERROR",
	3: "ALREADY_SIGNUP",
	4: "INVALID_CAPTCHA",
	5: "INVALID_USERID",
	6: "ALREADY_DEVICE",
	7: "INVALID_DEVICE",
}
var ErrorType_value = map[string]int32{
	"NONE_ERROR":      0,
	"INVALID_PARAM":   1,
	"INTERNAL_ERROR":  2,
	"ALREADY_SIGNUP":  3,
	"INVALID_CAPTCHA": 4,
	"INVALID_USERID":  5,
	"ALREADY_DEVICE":  6,
	"INVALID_DEVICE":  7,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// User class
// not for orm, just for easy code
type User struct {
	UserID  string    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Email   string    `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Mobile  string    `protobuf:"bytes,3,opt,name=mobile" json:"mobile,omitempty"`
	Pass    string    `protobuf:"bytes,4,opt,name=pass" json:"pass,omitempty"`
	Nick    string    `protobuf:"bytes,5,opt,name=nick" json:"nick,omitempty"`
	Devices []*Device `protobuf:"bytes,6,rep,name=devices" json:"devices,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

// user device
type Device struct {
	UserID    string    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	DeviceID  string    `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty"`
	Os        DeviceOS  `protobuf:"varint,3,opt,name=os,enum=protos.DeviceOS" json:"os,omitempty"`
	OsVersion string    `protobuf:"bytes,4,opt,name=osVersion" json:"osVersion,omitempty"`
	For       DeviceFor `protobuf:"varint,5,opt,name=for,enum=protos.DeviceFor" json:"for,omitempty"`
	Mac       string    `protobuf:"bytes,6,opt,name=mac" json:"mac,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Error struct {
	ErrorType ErrorType `protobuf:"varint,1,opt,name=errorType,enum=protos.ErrorType" json:"errorType,omitempty"`
	Message   string    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// AcquireCaptchaReq holds request
type AcquireCaptchaReq struct {
	SignUpType SignUpType `protobuf:"varint,1,opt,name=signUpType,enum=protos.SignUpType" json:"signUpType,omitempty"`
	SignUp     string     `protobuf:"bytes,2,opt,name=signUp" json:"signUp,omitempty"`
}

func (m *AcquireCaptchaReq) Reset()                    { *m = AcquireCaptchaReq{} }
func (m *AcquireCaptchaReq) String() string            { return proto.CompactTextString(m) }
func (*AcquireCaptchaReq) ProtoMessage()               {}
func (*AcquireCaptchaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type AcquireCaptchaRsp struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *AcquireCaptchaRsp) Reset()                    { *m = AcquireCaptchaRsp{} }
func (m *AcquireCaptchaRsp) String() string            { return proto.CompactTextString(m) }
func (*AcquireCaptchaRsp) ProtoMessage()               {}
func (*AcquireCaptchaRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AcquireCaptchaRsp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VerifyCaptchaReq struct {
	SignUpType SignUpType `protobuf:"varint,1,opt,name=signUpType,enum=protos.SignUpType" json:"signUpType,omitempty"`
	SignUp     string     `protobuf:"bytes,2,opt,name=signUp" json:"signUp,omitempty"`
	Captcha    string     `protobuf:"bytes,3,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *VerifyCaptchaReq) Reset()                    { *m = VerifyCaptchaReq{} }
func (m *VerifyCaptchaReq) String() string            { return proto.CompactTextString(m) }
func (*VerifyCaptchaReq) ProtoMessage()               {}
func (*VerifyCaptchaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type VerifyCaptchaRsp struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *VerifyCaptchaRsp) Reset()                    { *m = VerifyCaptchaRsp{} }
func (m *VerifyCaptchaRsp) String() string            { return proto.CompactTextString(m) }
func (*VerifyCaptchaRsp) ProtoMessage()               {}
func (*VerifyCaptchaRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *VerifyCaptchaRsp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RegisterUserReq struct {
	SignUpType SignUpType `protobuf:"varint,1,opt,name=signUpType,enum=protos.SignUpType" json:"signUpType,omitempty"`
	SignUp     string     `protobuf:"bytes,2,opt,name=signUp" json:"signUp,omitempty"`
	Nick       string     `protobuf:"bytes,3,opt,name=nick" json:"nick,omitempty"`
	Pass       string     `protobuf:"bytes,4,opt,name=pass" json:"pass,omitempty"`
}

func (m *RegisterUserReq) Reset()                    { *m = RegisterUserReq{} }
func (m *RegisterUserReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserReq) ProtoMessage()               {}
func (*RegisterUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RegisterUserRsp struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	User  *User  `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *RegisterUserRsp) Reset()                    { *m = RegisterUserRsp{} }
func (m *RegisterUserRsp) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserRsp) ProtoMessage()               {}
func (*RegisterUserRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RegisterUserRsp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RegisterUserRsp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type BindDeviceReq struct {
	UserID    string    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Os        DeviceOS  `protobuf:"varint,2,opt,name=os,enum=protos.DeviceOS" json:"os,omitempty"`
	OsVersion string    `protobuf:"bytes,3,opt,name=osVersion" json:"osVersion,omitempty"`
	For       DeviceFor `protobuf:"varint,4,opt,name=for,enum=protos.DeviceFor" json:"for,omitempty"`
	Mac       string    `protobuf:"bytes,5,opt,name=mac" json:"mac,omitempty"`
}

func (m *BindDeviceReq) Reset()                    { *m = BindDeviceReq{} }
func (m *BindDeviceReq) String() string            { return proto.CompactTextString(m) }
func (*BindDeviceReq) ProtoMessage()               {}
func (*BindDeviceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type BindDeviceRsp struct {
	Error  *Error  `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Device *Device `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
}

func (m *BindDeviceRsp) Reset()                    { *m = BindDeviceRsp{} }
func (m *BindDeviceRsp) String() string            { return proto.CompactTextString(m) }
func (*BindDeviceRsp) ProtoMessage()               {}
func (*BindDeviceRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BindDeviceRsp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BindDeviceRsp) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type VerifyDeviceReq struct {
	DeviceID string    `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	For      DeviceFor `protobuf:"varint,2,opt,name=for,enum=protos.DeviceFor" json:"for,omitempty"`
}

func (m *VerifyDeviceReq) Reset()                    { *m = VerifyDeviceReq{} }
func (m *VerifyDeviceReq) String() string            { return proto.CompactTextString(m) }
func (*VerifyDeviceReq) ProtoMessage()               {}
func (*VerifyDeviceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type VerifyDeviceRsp struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *VerifyDeviceRsp) Reset()                    { *m = VerifyDeviceRsp{} }
func (m *VerifyDeviceRsp) String() string            { return proto.CompactTextString(m) }
func (*VerifyDeviceRsp) ProtoMessage()               {}
func (*VerifyDeviceRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *VerifyDeviceRsp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "protos.User")
	proto.RegisterType((*Device)(nil), "protos.Device")
	proto.RegisterType((*Error)(nil), "protos.Error")
	proto.RegisterType((*AcquireCaptchaReq)(nil), "protos.AcquireCaptchaReq")
	proto.RegisterType((*AcquireCaptchaRsp)(nil), "protos.AcquireCaptchaRsp")
	proto.RegisterType((*VerifyCaptchaReq)(nil), "protos.VerifyCaptchaReq")
	proto.RegisterType((*VerifyCaptchaRsp)(nil), "protos.VerifyCaptchaRsp")
	proto.RegisterType((*RegisterUserReq)(nil), "protos.RegisterUserReq")
	proto.RegisterType((*RegisterUserRsp)(nil), "protos.RegisterUserRsp")
	proto.RegisterType((*BindDeviceReq)(nil), "protos.BindDeviceReq")
	proto.RegisterType((*BindDeviceRsp)(nil), "protos.BindDeviceRsp")
	proto.RegisterType((*VerifyDeviceReq)(nil), "protos.VerifyDeviceReq")
	proto.RegisterType((*VerifyDeviceRsp)(nil), "protos.VerifyDeviceRsp")
	proto.RegisterEnum("protos.SignUpType", SignUpType_name, SignUpType_value)
	proto.RegisterEnum("protos.DeviceOS", DeviceOS_name, DeviceOS_value)
	proto.RegisterEnum("protos.DeviceFor", DeviceFor_name, DeviceFor_value)
	proto.RegisterEnum("protos.ErrorType", ErrorType_name, ErrorType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for IDPP service

type IDPPClient interface {
	// Acquire email/tel captcha
	AcquireCaptcha(ctx context.Context, in *AcquireCaptchaReq, opts ...grpc.CallOption) (*AcquireCaptchaRsp, error)
	// Verify email/tel captcha
	VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaRsp, error)
	// Register a user
	RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRsp, error)
	// Bind a device for a user
	BindDeviceForUser(ctx context.Context, in *BindDeviceReq, opts ...grpc.CallOption) (*BindDeviceRsp, error)
}

type iDPPClient struct {
	cc *grpc.ClientConn
}

func NewIDPPClient(cc *grpc.ClientConn) IDPPClient {
	return &iDPPClient{cc}
}

func (c *iDPPClient) AcquireCaptcha(ctx context.Context, in *AcquireCaptchaReq, opts ...grpc.CallOption) (*AcquireCaptchaRsp, error) {
	out := new(AcquireCaptchaRsp)
	err := grpc.Invoke(ctx, "/protos.IDPP/AcquireCaptcha", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDPPClient) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaRsp, error) {
	out := new(VerifyCaptchaRsp)
	err := grpc.Invoke(ctx, "/protos.IDPP/VerifyCaptcha", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDPPClient) RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRsp, error) {
	out := new(RegisterUserRsp)
	err := grpc.Invoke(ctx, "/protos.IDPP/RegisterUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDPPClient) BindDeviceForUser(ctx context.Context, in *BindDeviceReq, opts ...grpc.CallOption) (*BindDeviceRsp, error) {
	out := new(BindDeviceRsp)
	err := grpc.Invoke(ctx, "/protos.IDPP/BindDeviceForUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IDPP service

type IDPPServer interface {
	// Acquire email/tel captcha
	AcquireCaptcha(context.Context, *AcquireCaptchaReq) (*AcquireCaptchaRsp, error)
	// Verify email/tel captcha
	VerifyCaptcha(context.Context, *VerifyCaptchaReq) (*VerifyCaptchaRsp, error)
	// Register a user
	RegisterUser(context.Context, *RegisterUserReq) (*RegisterUserRsp, error)
	// Bind a device for a user
	BindDeviceForUser(context.Context, *BindDeviceReq) (*BindDeviceRsp, error)
}

func RegisterIDPPServer(s *grpc.Server, srv IDPPServer) {
	s.RegisterService(&_IDPP_serviceDesc, srv)
}

func _IDPP_AcquireCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireCaptchaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDPPServer).AcquireCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IDPP/AcquireCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDPPServer).AcquireCaptcha(ctx, req.(*AcquireCaptchaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDPP_VerifyCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCaptchaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDPPServer).VerifyCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IDPP/VerifyCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDPPServer).VerifyCaptcha(ctx, req.(*VerifyCaptchaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDPP_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDPPServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IDPP/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDPPServer).RegisterUser(ctx, req.(*RegisterUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDPP_BindDeviceForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDPPServer).BindDeviceForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IDPP/BindDeviceForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDPPServer).BindDeviceForUser(ctx, req.(*BindDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IDPP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.IDPP",
	HandlerType: (*IDPPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireCaptcha",
			Handler:    _IDPP_AcquireCaptcha_Handler,
		},
		{
			MethodName: "VerifyCaptcha",
			Handler:    _IDPP_VerifyCaptcha_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _IDPP_RegisterUser_Handler,
		},
		{
			MethodName: "BindDeviceForUser",
			Handler:    _IDPP_BindDeviceForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for IDPA service

type IDPAClient interface {
	// Verify device
	VerifyDevice(ctx context.Context, in *VerifyDeviceReq, opts ...grpc.CallOption) (*VerifyDeviceRsp, error)
}

type iDPAClient struct {
	cc *grpc.ClientConn
}

func NewIDPAClient(cc *grpc.ClientConn) IDPAClient {
	return &iDPAClient{cc}
}

func (c *iDPAClient) VerifyDevice(ctx context.Context, in *VerifyDeviceReq, opts ...grpc.CallOption) (*VerifyDeviceRsp, error) {
	out := new(VerifyDeviceRsp)
	err := grpc.Invoke(ctx, "/protos.IDPA/VerifyDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IDPA service

type IDPAServer interface {
	// Verify device
	VerifyDevice(context.Context, *VerifyDeviceReq) (*VerifyDeviceRsp, error)
}

func RegisterIDPAServer(s *grpc.Server, srv IDPAServer) {
	s.RegisterService(&_IDPA_serviceDesc, srv)
}

func _IDPA_VerifyDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDPAServer).VerifyDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IDPA/VerifyDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDPAServer).VerifyDevice(ctx, req.(*VerifyDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IDPA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.IDPA",
	HandlerType: (*IDPAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyDevice",
			Handler:    _IDPA_VerifyDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("idp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x4f, 0xdb, 0x4a,
	0x14, 0xc5, 0x8e, 0xe3, 0x90, 0x1b, 0x92, 0x38, 0xf3, 0xf4, 0xf4, 0xf2, 0xa2, 0x8a, 0x22, 0xb7,
	0xaa, 0x50, 0x16, 0xb4, 0x4d, 0xf7, 0x95, 0x4c, 0x6c, 0x60, 0x8a, 0x63, 0x47, 0x76, 0x12, 0xa8,
	0xba, 0x40, 0x21, 0x18, 0x6a, 0x95, 0xc4, 0xc6, 0x03, 0x95, 0x58, 0x74, 0xdf, 0x9f, 0xd1, 0x5d,
	0xff, 0x66, 0xe7, 0x23, 0x26, 0x76, 0x08, 0x4a, 0x25, 0x56, 0x9e, 0xb9, 0x1f, 0xe7, 0x9e, 0x3b,
	0x73, 0xcf, 0x18, 0xca, 0xe1, 0x45, 0xbc, 0x17, 0x27, 0xd1, 0x6d, 0x84, 0x54, 0xfe, 0x21, 0x7a,
	0x02, 0xca, 0x90, 0x04, 0x09, 0xaa, 0x81, 0x7a, 0x47, 0xbf, 0xd8, 0x6c, 0x4a, 0x3b, 0xd2, 0x6e,
	0x19, 0x55, 0xa1, 0x18, 0x4c, 0xc7, 0xe1, 0x75, 0x53, 0xe6, 0x5b, 0xea, 0x9e, 0x46, 0xe7, 0xe1,
	0x75, 0xd0, 0x2c, 0xf0, 0xfd, 0x16, 0x28, 0xf1, 0x98, 0x90, 0xa6, 0x92, 0xee, 0x66, 0xe1, 0xe4,
	0x5b, 0xb3, 0xc8, 0x77, 0x2f, 0xa1, 0x74, 0x11, 0x7c, 0x0f, 0x27, 0x01, 0x69, 0xaa, 0x3b, 0x85,
	0xdd, 0x4a, 0xa7, 0x26, 0x6a, 0x92, 0x3d, 0x93, 0x9b, 0xf5, 0x9f, 0x12, 0xa8, 0x62, 0xf9, 0xa8,
	0xac, 0x06, 0x9b, 0x22, 0x97, 0x5a, 0x44, 0xe5, 0x17, 0x20, 0x47, 0x84, 0x57, 0xad, 0x75, 0xb4,
	0x3c, 0x90, 0xeb, 0xa3, 0x06, 0x94, 0x23, 0x32, 0x0a, 0x12, 0x12, 0x46, 0xb3, 0x39, 0x99, 0x6d,
	0x28, 0x5c, 0x46, 0x09, 0xe7, 0x52, 0xeb, 0x34, 0xf2, 0x19, 0x07, 0x51, 0x82, 0x2a, 0x50, 0x98,
	0x8e, 0x27, 0x94, 0x1a, 0x0d, 0xd6, 0x3f, 0x42, 0xd1, 0x4a, 0x12, 0x6a, 0x7d, 0x0d, 0xe5, 0x80,
	0x2d, 0x06, 0xf7, 0x71, 0xc0, 0xb9, 0x64, 0x72, 0xad, 0xd4, 0x81, 0xea, 0x50, 0x9a, 0x06, 0x84,
	0x8c, 0xaf, 0x02, 0xc1, 0x4e, 0x3f, 0x86, 0x86, 0x31, 0xb9, 0xb9, 0x0b, 0x93, 0xa0, 0x3b, 0x8e,
	0x6f, 0x27, 0x5f, 0xc7, 0x5e, 0x70, 0x83, 0xde, 0x00, 0x90, 0xf0, 0x6a, 0x36, 0x8c, 0x33, 0x60,
	0x28, 0x05, 0xf3, 0x1f, 0x3c, 0xac, 0x79, 0x11, 0x37, 0x07, 0x7b, 0xff, 0x08, 0x8c, 0xc4, 0xb4,
	0xff, 0x22, 0x27, 0xc6, 0x71, 0x2a, 0x9d, 0x6a, 0x8e, 0x94, 0xfe, 0x05, 0x34, 0xda, 0x7d, 0x78,
	0x79, 0xff, 0xfc, 0xf2, 0xac, 0xb9, 0x89, 0x40, 0x11, 0x97, 0xac, 0xbf, 0x5b, 0x06, 0x5f, 0x4b,
	0x27, 0x80, 0xba, 0x17, 0x5c, 0x85, 0xe4, 0x36, 0x48, 0xd8, 0x54, 0x3d, 0x87, 0x4d, 0x3a, 0x53,
	0x2b, 0xe6, 0x8d, 0x9e, 0x7a, 0xbe, 0xcc, 0x3a, 0x5e, 0xa8, 0x05, 0x0a, 0x1b, 0x33, 0x0e, 0x5d,
	0xe9, 0x6c, 0xa5, 0x4e, 0x96, 0xac, 0xff, 0x80, 0xea, 0x7e, 0x38, 0xbb, 0x10, 0x03, 0xc2, 0x18,
	0x2f, 0xcf, 0xa4, 0x98, 0x40, 0xf9, 0x6f, 0x26, 0xb0, 0x90, 0x9d, 0x40, 0x65, 0xcd, 0x04, 0x72,
	0xb5, 0xe8, 0xbd, 0x5c, 0xf9, 0xb5, 0x9d, 0x6c, 0x83, 0x2a, 0x04, 0x32, 0xef, 0x65, 0x59, 0x5b,
	0x5d, 0xa8, 0x8b, 0x3b, 0x5b, 0xf4, 0x93, 0xd5, 0x94, 0x94, 0x25, 0x28, 0x3f, 0x41, 0x50, 0x7f,
	0xbb, 0x04, 0xb2, 0x8e, 0x55, 0xfb, 0x15, 0x40, 0xe6, 0x2a, 0xcb, 0x54, 0x54, 0x3d, 0x03, 0xdb,
	0xda, 0x06, 0x02, 0x50, 0x7b, 0xee, 0x3e, 0xb6, 0x2d, 0x4d, 0x6a, 0x9f, 0xc2, 0xe6, 0xc3, 0xa9,
	0x55, 0xa0, 0x34, 0x74, 0x8e, 0x5d, 0xe7, 0xc4, 0xa1, 0x41, 0x25, 0x28, 0xf4, 0x8c, 0xae, 0x26,
	0xb1, 0x44, 0x1b, 0x3b, 0xc3, 0x53, 0x4d, 0x46, 0x9b, 0xf4, 0x5d, 0x72, 0xf0, 0xa9, 0x56, 0x60,
	0xa1, 0x27, 0xd8, 0x31, 0xdd, 0x13, 0x5f, 0x53, 0x58, 0x28, 0x76, 0x7d, 0xad, 0xc8, 0xac, 0x86,
	0x63, 0x7a, 0x2e, 0x36, 0x35, 0xb5, 0xed, 0x42, 0x79, 0x71, 0xba, 0xb4, 0xe4, 0x81, 0xe1, 0xf5,
	0x2c, 0x4f, 0x94, 0xb7, 0x2d, 0xf3, 0x90, 0xae, 0x25, 0xb6, 0x1e, 0x58, 0xb6, 0x4d, 0xd7, 0x32,
	0xbd, 0x62, 0xf0, 0x87, 0x7d, 0xcb, 0x1b, 0x61, 0xdf, 0xf5, 0x68, 0x0d, 0xba, 0xc7, 0x66, 0xdf,
	0x73, 0x47, 0xd8, 0xa4, 0x7e, 0xa5, 0xfd, 0x5b, 0x82, 0xf2, 0x42, 0xf5, 0xd4, 0xeb, 0xb8, 0x8e,
	0x75, 0x66, 0x79, 0x9e, 0xcb, 0x50, 0x1b, 0x50, 0xc5, 0xce, 0xc8, 0xb0, 0xb1, 0x79, 0xd6, 0x37,
	0x3c, 0xa3, 0x47, 0xc1, 0x11, 0xd4, 0xb0, 0x33, 0xb0, 0x3c, 0xc7, 0xb0, 0xe7, 0x61, 0x32, 0xb3,
	0x19, 0xb6, 0x67, 0x19, 0xe6, 0xe7, 0x33, 0x1f, 0x1f, 0x3a, 0xc3, 0x3e, 0x2d, 0xf4, 0x0f, 0xd4,
	0xd3, 0xd4, 0xae, 0xd1, 0x1f, 0x74, 0x8f, 0x0c, 0xda, 0x14, 0x4f, 0x16, 0xc6, 0xa1, 0x6f, 0x79,
	0xb4, 0xa5, 0x62, 0x36, 0xd9, 0xb4, 0x46, 0xb8, 0x6b, 0x69, 0x6a, 0x36, 0x6e, 0x6e, 0x2b, 0x75,
	0x7e, 0xc9, 0xa0, 0x50, 0xea, 0x7d, 0x74, 0x44, 0x13, 0x72, 0x8f, 0x07, 0xfa, 0x3f, 0xbd, 0xa3,
	0x47, 0x2f, 0x54, 0xeb, 0x29, 0x17, 0x89, 0xf5, 0x0d, 0x64, 0x41, 0x35, 0x27, 0x7b, 0xd4, 0x4c,
	0xa3, 0x97, 0x9f, 0x9a, 0xd6, 0x13, 0x1e, 0x0e, 0xb3, 0x0f, 0x5b, 0x59, 0x91, 0xa2, 0xff, 0xd2,
	0xd8, 0xa5, 0x17, 0xa2, 0xb5, 0xda, 0xc1, 0x31, 0xba, 0xd0, 0x58, 0x88, 0x83, 0x5e, 0x2e, 0x07,
	0xfa, 0x37, 0x8d, 0xcf, 0xc9, 0xb6, 0xb5, 0xca, 0xcc, 0x40, 0x3a, 0x9f, 0xf8, 0x09, 0x19, 0x8c,
	0x50, 0x76, 0xaa, 0x17, 0x84, 0x96, 0x04, 0xd3, 0x5a, 0xed, 0x60, 0x58, 0xe7, 0xe2, 0xb7, 0xf9,
	0xe1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x3b, 0xbf, 0x06, 0x4a, 0x07, 0x00, 0x00,
}
